### ISSUE TITLE
Bug: Vanilla feature disappears

### ISSUE THREAD

**Issue by linzexin022** [mschae23/grind-enchantments#25]
In vanilla, I can grind 2 curse books into 1 item of 2 copies.
![2022-06-09_09 54 19](https://user-images.githubusercontent.com/59003232/172748499-a94e68b2-f370-4c91-b628-2d8e7e375858.png)
However, when this mod enabled, this feature disappears.
![2022-06-09_09 56 39](https://user-images.githubusercontent.com/59003232/172748595-fc8a1b5f-6600-4a33-8e3c-6cfb058fe8f4.png)

**Comment by mschae23** [comment]
Interesting, I didn't even know that feature existed (it doesn't really make sense either, because items with NBT data usually can't stack). I'll try to fix this.

**Comment by mschae23** [comment]
I've found the cause: when two enchanted books are in the grindstone's slots, the "move enchantments" feature tries to move the first enchantment of the first book to the second one. However, that only works if the book has at least two non-curse enchantments.
I've now changed it to keep the vanilla behaviour in this case instead of blocking the output slot (in version 1.6.4).
