### ISSUE TITLE
not working 1.18.2

### ISSUE THREAD

**Issue by Balakay420** [mschae23/grind-enchantments#36]
hey, i have the mod installed but it doesnt work. is there any known conflictions?

**Comment by mschae23** [comment]
There is a known conflict with Charm, but other than that, I can't help you much without further information.
Do you have a log file (latest file in `.minecraft/logs`)?

**Comment by Balakay420** [comment]
https://paste.gg/p/anonymous/8b98ba6caeda4912a450e937941471db
![2023-02-02_06 33 51](https://user-images.githubusercontent.com/106470691/216327468-8622d1c4-1ae9-44db-8edd-dff2c81a87a5.png)
![2023-02-02_06 33 53](https://user-images.githubusercontent.com/106470691/216327475-be93f043-59fb-4016-af80-13f3d5a9d7e7.png)
![2023-02-02_06 35 53](https://user-images.githubusercontent.com/106470691/216327478-5e2e8096-0efa-484a-a659-ec4a6d6822b7.png)

**Comment by mschae23** [comment]
Alright, the mod seems to be loading properly and without errors, so I can't directly see where the problem is.
And with that many mods, it is unfortunately very likely to be some kind of conflict with another mod that modifies the grindstone.
You can try using the mod by itself, and if that works, it would confirm that this is a compatibility issue. Unless you happen to find what specific mod it conflicts with though, I don't believe I can do much about this.
