### ISSUE TITLE
Crashing game during startup (1.19.2)

### ISSUE THREAD

**Issue by KB-Q** [mschae23/grind-enchantments#38]
**java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'grindenchantments'!**

Mod version: grind-enchantments-3.0.0-beta.1+1.19.3.jar
Minecraft version: 1.19.2 (Fabric)

Here's the crash report: https://paste.ee/p/haiwa

**Comment by mschae23** [comment]
`class_7225$class_7874` is not found, which seems to be `RegistryWrapper.WrapperLookup`.
I don't remember using that (and the stacktrace is not particularly helpful), so I will have to debug that further.

As a workaround, you could try using either the 2.0.0 version (which is also for 1.19.3, but it could potentially not have this issue due to changes in 3.0.0), or the one for 1.19.2, which I apparently forgot to publish on Modrinth (I assume you are using that, as 3.0.0-beta.1 is not on CurseForge).

**Comment by mschae23** [comment]
I have now uploaded a new version on Modrinth that is built against 1.19.2, which should fix this issue.
