### ISSUE TITLE
Can't see or collect an enchanted book. User error?

### ISSUE THREAD

**Issue by ejm554** [mschae23/grind-enchantments#61]
Hello. I've been trying this mod for the first time, but I'm having trouble collecting an enchanted book. I can briefly get the enchanted book to appear, but it disappears a fraction of a second after I add a regular book to the grindstone. 

I don't have a lot of experience adding mods to my server, so I'm not sure if these issues are a result of bug(s), or if they are due to user error. 

See [video](https://github.com/user-attachments/assets/9db10c4a-1ea3-4f90-a6da-231832357bd0) for details. (13 seconds) 
- The first few seconds shows what it looks like when clicking & dragging a book from my inventory. 
- The remainder shows attempts to add the same book via Shift+Clicking.

Also, I cannot locate a `config` file anywhere. 
- Where should this be? 
- If it doesn't exist, does this indicate a problem? 
- If it is a problem, any thoughts on how to resolve?

Specs: 
- Minecraft 1.20.6 running on a Paper server (build 148).
- On **server**: mod and Fabric API installed in `mod` folder
   - `fabric-api-0.100.4 1.20.6`
   - `grind-enchantments-3.2.1 1.20.6`
 - On **client**: same as above, _plus_ `Fabric Loader 0.15.11`
   - I'm not clear if Fabric Loader is also required on the server, or how I check if it is running/not running.

Logs:
- Server log [here](https://mclo.gs/tRmjgh3).
  - The server log makes no reference to the mod, nor Fabric. I'm not sure if this is normal.
- Client log [here](https://mclo.gs/HBfijCg).
   - I see no obvious errors in client log.
   - However, lines 219-220 shows `codec-config-api 2.0.0 1.20.5-rc3` as a subitem to the mod. Is it okay that the API is not referring to 1.20.6?

**Comment by mschae23** [comment]
Hello! Thank you for the detailed report.

The mod is required on the server, and optional on the client. I believe Paper does not support Fabric mods, which means it will just be ignored there. The consequence is that it is only installed on the client – that is what causes these flashes of the enchantment book appearing, since the client *thinks* that's what's supposed to happen, but then the server sends back the vanilla result.

You probably only have two options if you do want to have this functionality:
1. Search for a Paper plugin that does this (I'm not familiar with those, so I can't point you to one, unfortunately).
2. Install Fabric on the server instead of Paper.

> Also, I cannot locate a config file anywhere.

The config file is only generated on the logical server side, so it wouldn't appear on your dedicated server. However, it should be there on your client, at `.minecraft/config/grindenchantments.json`. Note that changing it on the client will only have an effect on the displayed XP cost, not the actual one.

> [...] lines 219-220 shows `codec-config-api 2.0.0 1.20.5-rc3` as a subitem to the mod. Is it okay that the API is not referring to 1.20.6?

That library only touches a small part of Minecraft that rarely changes, so it usually works across versions.
