### ISSUE TITLE
isnt meant for the right java

### ISSUE THREAD

**Issue by Queenelizardbeth** [mschae23/grind-enchantments#72]
basically its made for java 21 but the version uses java 17

**Comment by Poopooracoocoo** [comment]
@mschae23 Yes. More specifically the issue is with Codec Config API, which this mod includes.

**Comment by mschae23** [comment]
> More specifically the issue is with Codec Config API, which this mod includes.

That one [should](https://github.com/mschae23/codec-config-api/blob/1.20.1/build.gradle#L35) use Java 17 as well - but I think I'll just recompile with Java 17 directly, seems easier than relying on compatibility options.

**Comment by mschae23** [comment]
I've uploaded version 3.1.4+1.20.1 now, which fixes this issue. It's unfortunate that this was caused by the Mixin configuration even though codec config API doesn't even have any mixins, but it should be working now.

It's just a bit annoying that CurseForge will now mark 1.20.1 as the mod's main "game version", because it is the last release...
